// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    AModal: typeof import('ant-design-vue/es')['Modal'];
    Header: typeof import('./src/components/Header.vue')['default'];
    Icons: typeof import('./src/components/Icons.vue')['default'];
    Meta2d: typeof import('./src/components/Meta2d.vue')['default'];
    Meta2dTwo: typeof import('./src/components/Meta2dTwo.vue')['default'];
  }
}

export {};
