// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AModal: typeof import('ant-design-vue/es')['Modal']
    Header: typeof import('./src/components')['Header']
    Icons: typeof import('./src/components')['Icons']
    Topology: typeof import('./src/components')['Topology']
  }
}

export { }
