name: "bug报告"
description: "向我们反馈项目出现的意外错误."
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    attributes:
      label: Code Sanbox异常重现
      description: |
        请提供重现的Sanbox链接，以便开发人员快速定位
      placeholder: |
        e.g.  Code Sandbox 链接
    validations:
      required: false
  - type: textarea
    attributes:
      label: bug描述
      description: |
        发生了什么错误
      placeholder: |
        描述您遇到的问题
    validations:
      required: true
  - type: textarea
    attributes:
      label: 期待效果
      description: |
        你期待出现的效果
      placeholder: |
        你期待出现的效果
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 发生频率
      description: |
        这个bug发生的频率是多久
      options:
        - 每次
        - 经常
        - 偶尔
        - 一次
    validations:
      required: true
  - type: input
    attributes:
      label: 核心库版本
      description: |
        相关核心库版本号
  - type: input
    attributes:
      label: 浏览器版本
      description: |
        请输入浏览器版本信息
  - type: textarea
    attributes:
      label: 其他需要补充的
      description: |
        请输入需要额外补充的内容
